# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["brad@bradchoate.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-typescript"
description = "Fastly Edge Compute service for MLTSHP"
language = "javascript"
manifest_version = 3
name = "mltshp-fastly-edge"
service_id = ""

[scripts]
  build = "npm run build"
  post_init = "npm install"
